export const DEFAULT_BAR_WIDTH = 32
export const DEFAULT_MIN_DISTANCE_BETWEEN_BARS = 8
export const DEFAULT_MAX_DISTANCE_BETWEEN_BARS = 32
export const DEFAULT_MIN_DISTANCE_BETWEEN_BAR_GROUPS = 16
export const DEFAULT_MAX_DISTANCE_BETWEEN_BAR_GROUPS = 32
export const DEFAULT_DISTANCE_BETWEEN_BARS_IN_GROUP = 8
export const SCALE_TOP_OFFSET = 0.12
export const DEFAULT_BAR_CORNER_RADIUS = 6
