const comments = `
  /*
    THIS FILE IS GENERATED BY ICON BUILD TOOL
    DO NOT EDIT IT MANUAL
    Docs in @kaspersky/hexa-ui-icons package
  */
`

/**
 * template
 * @param componentName - The component name
 * @param props - The properties
 * @param interfaces - All necessary interfaces (typescript)
 * @param imports - All necessary imports
 * @param exports - The export of the component
 * @param jsx - The JSX part of the component
 * @returns A built-in template-tag function to create template
 */
const propTypesTemplate = (
  { componentName, jsx },
  { tpl }
) => {
  const iconName = componentName.replace('Svg', '')
  return tpl`
  ${comments}
  
  import React, { type ComponentProps, type SVGProps } from 'react'
  // @ts-ignore
  import { resolveColorToken } from '../helpers/resolveColorToken'
  import type { ITestIds } from './index'
  const Icon = React.forwardRef<SVGSVGElement, SVGProps<SVGSVGElement>>((props, ref) => ${jsx})
  type CustomComponentProps = ComponentProps<typeof Icon> & ITestIds
  const _CustomComponent = React.memo(
    React.forwardRef<SVGSVGElement, CustomComponentProps>((props, ref) => {
      const { klId, testId, ...otherProps } = props
      return <Icon kl-id={klId} data-testid={testId} ref={ref} {...otherProps} /> 
    })
  )
  const ${iconName} = _CustomComponent
  ${iconName}.displayName = '${iconName}'
  export default ${iconName}
  `
}

module.exports = propTypesTemplate
