import { ComponentType } from 'react'

export const AboutProduct: ComponentType<any>
export const Account: ComponentType<any>
export const AccountCheck: ComponentType<any>
export const AccountID: ComponentType<any>
export const Accounts: ComponentType<any>
export const AccountUser: ComponentType<any>
export const ActivityMonitor: ComponentType<any>
export const Address: ComponentType<any>
export const Alarm: ComponentType<any>
export const Antibanner: ComponentType<any>
export const Antitheft: ComponentType<any>
export const App: ComponentType<any>
export const AppActivity: ComponentType<any>
export const AppClean: ComponentType<any>
export const AppControl: ComponentType<any>
export const AppLayout: ComponentType<any>
export const AppUpdate: ComponentType<any>
export const Attention: ComponentType<any>
export const AutoCar: ComponentType<any>
export const Backup: ComponentType<any>
export const BookHelp: ComponentType<any>
export const BrowserConfiguration: ComponentType<any>
export const Calendar: ComponentType<any>
export const CameraIP: ComponentType<any>
export const CameraWeb: ComponentType<any>
export const CardSafeMoney: ComponentType<any>
export const Cloud: ComponentType<any>
export const Collectors: ComponentType<any>
export const Computer: ComponentType<any>
export const Connect: ComponentType<any>
export const ConnectionOff: ComponentType<any>
export const Contacts: ComponentType<any>
export const Danger: ComponentType<any>
export const DataCleaner: ComponentType<any>
export const DataFeed: ComponentType<any>
export const Delete: ComponentType<any>
export const Desktop: ComponentType<any>
export const Doctor: ComponentType<any>
export const Download: ComponentType<any>
export const Error: ComponentType<any>
export const FileAntivirus: ComponentType<any>
export const FileProtection: ComponentType<any>
export const FileScan: ComponentType<any>
export const FileShredder: ComponentType<any>
export const FilesScans: ComponentType<any>
export const FileText: ComponentType<any>
export const FileThreat: ComponentType<any>
export const Firewall: ComponentType<any>
export const FlashDrive: ComponentType<any>
export const Folder: ComponentType<any>
export const FolderOpen: ComponentType<any>
export const Gamepad: ComponentType<any>
export const Groupe: ComponentType<any>
export const HardDriveMonitor: ComponentType<any>
export const HDD: ComponentType<any>
export const HomeDevice: ComponentType<any>
export const Info: ComponentType<any>
export const iPhone: ComponentType<any>
export const Keyboard: ComponentType<any>
export const Laptop: ComponentType<any>
export const License: ComponentType<any>
export const Lock: ComponentType<any>
export const LockSettings: ComponentType<any>
export const Mail: ComponentType<any>
export const ManagementConsole: ComponentType<any>
export const MediaStorage: ComponentType<any>
export const MemoryRAM: ComponentType<any>
export const Messages: ComponentType<any>
export const Multidevice: ComponentType<any>
export const Network: ComponentType<any>
export const NetworkAttack: ComponentType<any>
export const Notes: ComponentType<any>
export const Notification: ComponentType<any>
export const OK: ComponentType<any>
export const OK2: ComponentType<any>
export const ParentalControl: ComponentType<any>
export const PasswordHide: ComponentType<any>
export const PasswordManager: ComponentType<any>
export const PasswordShow: ComponentType<any>
export const PinLocation: ComponentType<any>
export const PinMapLocation: ComponentType<any>
export const Play: ComponentType<any>
export const Premium: ComponentType<any>
export const PremiumCrown: ComponentType<any>
export const Printer: ComponentType<any>
export const PrivacyCleaner: ComponentType<any>
export const PrivacyProtection: ComponentType<any>
export const ProtectionSettings: ComponentType<any>
export const Quarantine: ComponentType<any>
export const Question: ComponentType<any>
export const RefreshSync: ComponentType<any>
export const Reload: ComponentType<any>
export const Remotedesktop: ComponentType<any>
export const Reports: ComponentType<any>
export const RescueDiscCD: ComponentType<any>
export const Restore: ComponentType<any>
export const Router: ComponentType<any>
export const Safe: ComponentType<any>
export const SafeEmpty: ComponentType<any>
export const SafeFull: ComponentType<any>
export const Scan: ComponentType<any>
export const Scan2: ComponentType<any>
export const ScanRadar01: ComponentType<any>
export const ScanRadar02: ComponentType<any>
export const ScanRadar03: ComponentType<any>
export const ScanSearch: ComponentType<any>
export const Search: ComponentType<any>
export const Secrets: ComponentType<any>
export const Server: ComponentType<any>
export const Settings: ComponentType<any>
export const SettingsControl: ComponentType<any>
export const Shield: ComponentType<any>
export const Shield2: ComponentType<any>
export const ShieldCracked: ComponentType<any>
export const ShieldSelfdefense: ComponentType<any>
export const ShoppingCart: ComponentType<any>
export const Signs: ComponentType<any>
export const Smartphoneprotection: ComponentType<any>
export const Social: ComponentType<any>
export const Spam: ComponentType<any>
export const SSD: ComponentType<any>
export const Storage: ComponentType<any>
export const Support: ComponentType<any>
export const Support2: ComponentType<any>
export const Tag: ComponentType<any>
export const Tags: ComponentType<any>
export const Threats: ComponentType<any>
export const Tools: ComponentType<any>
export const TrustedAppMode: ComponentType<any>
export const TV: ComponentType<any>
export const UnknownDrive: ComponentType<any>
export const Upload: ComponentType<any>
export const UploadCloud: ComponentType<any>
export const Vpn: ComponentType<any>
export const VulnerabilityScan: ComponentType<any>
export const Wait: ComponentType<any>
export const Warning: ComponentType<any>
export const Web: ComponentType<any>
export const WebProtection: ComponentType<any>
export const WebProtection2: ComponentType<any>
