import { ComponentType } from 'react'

export const AccountLogin: ComponentType<any>
export const Add: ComponentType<any>
export const Address: ComponentType<any>
export const Advertisement: ComponentType<any>
export const Alarm: ComponentType<any>
export const AlarmOff: ComponentType<any>
export const Amazon: ComponentType<any>
export const Analytics: ComponentType<any>
export const Apple: ComponentType<any>
export const Apps: ComponentType<any>
export const Archive: ComponentType<any>
export const Arrowdown: ComponentType<any>
export const Arrowdown2: ComponentType<any>
export const Arrowup: ComponentType<any>
export const Arrowup2: ComponentType<any>
export const Attachment: ComponentType<any>
export const Back: ComponentType<any>
export const Backup: ComponentType<any>
export const Box: ComponentType<any>
export const Brand: ComponentType<any>
export const Calendar: ComponentType<any>
export const Cancel: ComponentType<any>
export const CardSafeMoney: ComponentType<any>
export const Category: ComponentType<any>
export const Check: ComponentType<any>
export const Clean: ComponentType<any>
export const Clear: ComponentType<any>
export const ClearText: ComponentType<any>
export const Cloud: ComponentType<any>
export const Code: ComponentType<any>
export const Comment: ComponentType<any>
export const Configure: ComponentType<any>
export const Connect: ComponentType<any>
export const ConnectionEthernet: ComponentType<any>
export const ConnectionEthernetOff: ComponentType<any>
export const ConnectionOff: ComponentType<any>
export const ConnectionWifi: ComponentType<any>
export const ConnectionWifiOff: ComponentType<any>
export const Copy: ComponentType<any>
export const Customsettings: ComponentType<any>
export const Cut: ComponentType<any>
export const Danger: ComponentType<any>
export const DashboardGrid: ComponentType<any>
export const DashboardPerformance: ComponentType<any>
export const DataFeeds: ComponentType<any>
export const Delete: ComponentType<any>
export const DeviceNew: ComponentType<any>
export const DeviceSearch: ComponentType<any>
export const DeviceServer: ComponentType<any>
export const DigitalFootprint: ComponentType<any>
export const Down: ComponentType<any>
export const Download: ComponentType<any>
export const DownMini: ComponentType<any>
export const DragDrop: ComponentType<any>
export const Dribbble: ComponentType<any>
export const Edit: ComponentType<any>
export const EmojiHappy: ComponentType<any>
export const EmojiSad: ComponentType<any>
export const Export: ComponentType<any>
export const F: ComponentType<any>
export const File: ComponentType<any>
export const FileError: ComponentType<any>
export const FileError2: ComponentType<any>
export const FileLoad: ComponentType<any>
export const FileUnknown: ComponentType<any>
export const Filter: ComponentType<any>
export const Flag: ComponentType<any>
export const Folder: ComponentType<any>
export const FolderNew: ComponentType<any>
export const FontBold: ComponentType<any>
export const FontItalic: ComponentType<any>
export const FontUnderstrike: ComponentType<any>
export const Gmail: ComponentType<any>
export const Google: ComponentType<any>
export const GroupCollapse: ComponentType<any>
export const GroupExpand: ComponentType<any>
export const Heart: ComponentType<any>
export const Help: ComponentType<any>
export const Hex: ComponentType<any>
export const Hide: ComponentType<any>
export const HistoryLogJournal: ComponentType<any>
export const Home: ComponentType<any>
export const Import: ComponentType<any>
export const Info: ComponentType<any>
export const IP: ComponentType<any>
export const Keyboard: ComponentType<any>
export const Left: ComponentType<any>
export const LeftMini: ComponentType<any>
export const License: ComponentType<any>
export const Licensekey: ComponentType<any>
export const Like: ComponentType<any>
export const Link: ComponentType<any>
export const LinkExternal: ComponentType<any>
export const LinkUnlink: ComponentType<any>
export const List: ComponentType<any>
export const Lock: ComponentType<any>
export const Login: ComponentType<any>
export const LogoutSignout: ComponentType<any>
export const Mail: ComponentType<any>
export const Maximize: ComponentType<any>
export const Menu01: ComponentType<any>
export const Menu02: ComponentType<any>
export const Menu03: ComponentType<any>
export const Messages: ComponentType<any>
export const Minimize: ComponentType<any>
export const Minus: ComponentType<any>
export const Multidevice: ComponentType<any>
export const Network: ComponentType<any>
export const Note: ComponentType<any>
export const Notification: ComponentType<any>
export const Password: ComponentType<any>
export const PasswordHide: ComponentType<any>
export const PasswordShow: ComponentType<any>
export const Pause: ComponentType<any>
export const PC: ComponentType<any>
export const Phone: ComponentType<any>
export const Pin: ComponentType<any>
export const Plus: ComponentType<any>
export const PremiumCrown: ComponentType<any>
export const Pricetable: ComponentType<any>
export const Print: ComponentType<any>
export const Quarantine: ComponentType<any>
export const Question: ComponentType<any>
export const Reload: ComponentType<any>
export const Reports01: ComponentType<any>
export const Reports02: ComponentType<any>
export const Resize: ComponentType<any>
export const Restore: ComponentType<any>
export const Right: ComponentType<any>
export const RightMini: ComponentType<any>
export const Run: ComponentType<any>
export const Safe: ComponentType<any>
export const SafeKids: ComponentType<any>
export const Sandbox: ComponentType<any>
export const Save: ComponentType<any>
export const SaveAs: ComponentType<any>
export const ScanRadar: ComponentType<any>
export const Search: ComponentType<any>
export const SecurityCheck: ComponentType<any>
export const Settings01: ComponentType<any>
export const Settings02: ComponentType<any>
export const Shield: ComponentType<any>
export const Shield2: ComponentType<any>
export const ShieldEnforced: ComponentType<any>
export const StatusError: ComponentType<any>
export const StatusOK: ComponentType<any>
export const Stop: ComponentType<any>
export const Store: ComponentType<any>
export const Subnet: ComponentType<any>
export const Support: ComponentType<any>
export const Table: ComponentType<any>
export const Target: ComponentType<any>
export const Task: ComponentType<any>
export const Thread: ComponentType<any>
export const Time: ComponentType<any>
export const TurnOver: ComponentType<any>
export const Tutorial: ComponentType<any>
export const Unlock: ComponentType<any>
export const Up: ComponentType<any>
export const Update: ComponentType<any>
export const UpMini: ComponentType<any>
export const UserAccount: ComponentType<any>
export const UsersGroup: ComponentType<any>
export const Video: ComponentType<any>
export const VirtualMachine: ComponentType<any>
export const Warning: ComponentType<any>
export const Web: ComponentType<any>
export const Window: ComponentType<any>
export const Windowlayout: ComponentType<any>
export const Wizard: ComponentType<any>
