import { ComponentType } from 'react'

export const Accessability: ComponentType<any>
export const Account: ComponentType<any>
export const Accountcheck: ComponentType<any>
export const Accountinfo: ComponentType<any>
export const Accounts: ComponentType<any>
export const Activitymonitor: ComponentType<any>
export const Add: ComponentType<any>
export const Add2: ComponentType<any>
export const Address: ComponentType<any>
export const AirConditioner: ComponentType<any>
export const Alarm: ComponentType<any>
export const AlertHigh: ComponentType<any>
export const AlertLow: ComponentType<any>
export const AlertMedium: ComponentType<any>
export const AlertTitle: ComponentType<any>
export const Antibanner: ComponentType<any>
export const Antitheft: ComponentType<any>
export const Antivirus: ComponentType<any>
export const Anysensor: ComponentType<any>
export const App: ComponentType<any>
export const AppActivity: ComponentType<any>
export const AppClean: ComponentType<any>
export const AppControl: ComponentType<any>
export const AppLayout: ComponentType<any>
export const AppLock: ComponentType<any>
export const Apps: ComponentType<any>
export const AppUpdate: ComponentType<any>
export const AppUpdate2: ComponentType<any>
export const Archive: ComponentType<any>
export const Baby: ComponentType<any>
export const BackAndroid: ComponentType<any>
export const Backspace: ComponentType<any>
export const Backup: ComponentType<any>
export const BackupDisabled: ComponentType<any>
export const BatteryCharge: ComponentType<any>
export const BatteryCharge2: ComponentType<any>
export const BatteryLife: ComponentType<any>
export const BatteryLoad: ComponentType<any>
export const BatteryUnknown: ComponentType<any>
export const Beartoy: ComponentType<any>
export const Beta: ComponentType<any>
export const Browser: ComponentType<any>
export const Browser2: ComponentType<any>
export const BrowserConfiguration: ComponentType<any>
export const BrowserNewweb: ComponentType<any>
export const Bulb: ComponentType<any>
export const BulbHintEurica: ComponentType<any>
export const Cablebox: ComponentType<any>
export const Calendar: ComponentType<any>
export const CallIncoming: ComponentType<any>
export const CallOutgoing: ComponentType<any>
export const CallSMS: ComponentType<any>
export const CameraIP: ComponentType<any>
export const CameraPhoto: ComponentType<any>
export const CameraWeb: ComponentType<any>
export const Cancel: ComponentType<any>
export const Car: ComponentType<any>
export const CardSafemoney: ComponentType<any>
export const Change: ComponentType<any>
export const Clock: ComponentType<any>
export const ClockRound: ComponentType<any>
export const Cloud: ComponentType<any>
export const CloudDisabled: ComponentType<any>
export const CloudUpload: ComponentType<any>
export const Computer: ComponentType<any>
export const Configure: ComponentType<any>
export const Connect: ComponentType<any>
export const ConnectionLAN: ComponentType<any>
export const ConnectionNoWifi: ComponentType<any>
export const ConnectionOff: ComponentType<any>
export const ConnectionWifi: ComponentType<any>
export const Copy: ComponentType<any>
export const Danger: ComponentType<any>
export const Datacleaner: ComponentType<any>
export const Delete: ComponentType<any>
export const Desktop: ComponentType<any>
export const Doorbell: ComponentType<any>
export const Download: ComponentType<any>
export const Edit: ComponentType<any>
export const Error: ComponentType<any>
export const File: ComponentType<any>
export const FileError: ComponentType<any>
export const FileImage: ComponentType<any>
export const FileOK: ComponentType<any>
export const Files: ComponentType<any>
export const FileSad: ComponentType<any>
export const FileScans: ComponentType<any>
export const FileText: ComponentType<any>
export const FileUnknown: ComponentType<any>
export const Firewall: ComponentType<any>
export const FlashDrive: ComponentType<any>
export const Folder: ComponentType<any>
export const Gamepad: ComponentType<any>
export const Gesture: ComponentType<any>
export const Grid: ComponentType<any>
export const Grid2: ComponentType<any>
export const HardDrive: ComponentType<any>
export const HardDriveMonitor: ComponentType<any>
export const HealthMonitor: ComponentType<any>
export const HistoryLogJournal: ComponentType<any>
export const Home: ComponentType<any>
export const HomeDevice: ComponentType<any>
export const HomeGarage: ComponentType<any>
export const Infinite: ComponentType<any>
export const Info: ComponentType<any>
export const Ipad: ComponentType<any>
export const iPhoneandiPad: ComponentType<any>
export const Keyboard: ComponentType<any>
export const KeyboardHide: ComponentType<any>
export const Kid: ComponentType<any>
export const KISAndroid: ComponentType<any>
export const Layers: ComponentType<any>
export const License1: ComponentType<any>
export const License2: ComponentType<any>
export const License3: ComponentType<any>
export const LicenseKey: ComponentType<any>
export const Link: ComponentType<any>
export const Lock: ComponentType<any>
export const Mail1: ComponentType<any>
export const Mail2: ComponentType<any>
export const MailSpam: ComponentType<any>
export const Map: ComponentType<any>
export const MediaStorage: ComponentType<any>
export const Memory: ComponentType<any>
export const Menu1: ComponentType<any>
export const Menu2: ComponentType<any>
export const Menu3: ComponentType<any>
export const Message: ComponentType<any>
export const Messages: ComponentType<any>
export const Microphone: ComponentType<any>
export const MotionDetector: ComponentType<any>
export const Multidevice: ComponentType<any>
export const Network1: ComponentType<any>
export const Network2: ComponentType<any>
export const NetworkAttack: ComponentType<any>
export const Nonotification1: ComponentType<any>
export const Nonotification2: ComponentType<any>
export const Notes: ComponentType<any>
export const Notification: ComponentType<any>
export const NotificationBell: ComponentType<any>
export const Ok: ComponentType<any>
export const OkCircle: ComponentType<any>
export const Openinwindow: ComponentType<any>
export const OSAndroid: ComponentType<any>
export const OSiOS: ComponentType<any>
export const OSmacOS: ComponentType<any>
export const OSWindows: ComponentType<any>
export const ParentalControl: ComponentType<any>
export const PasswordCheck: ComponentType<any>
export const PasswordHide: ComponentType<any>
export const PasswordManager: ComponentType<any>
export const PasswordProtected: ComponentType<any>
export const PasswordShow: ComponentType<any>
export const Pet: ComponentType<any>
export const PhoneAndroid: ComponentType<any>
export const PhoneError: ComponentType<any>
export const PhoneiPhone: ComponentType<any>
export const PhoneProtection: ComponentType<any>
export const Photoframe: ComponentType<any>
export const Placeholder: ComponentType<any>
export const Play: ComponentType<any>
export const Plugin: ComponentType<any>
export const Pointer: ComponentType<any>
export const Power: ComponentType<any>
export const Premium: ComponentType<any>
export const PremiumCrown: ComponentType<any>
export const Printer: ComponentType<any>
export const PrivacyCleaner: ComponentType<any>
export const PrivacyProtection: ComponentType<any>
export const PrizeCup: ComponentType<any>
export const Profile: ComponentType<any>
export const ProfileCustom: ComponentType<any>
export const ProfileOld: ComponentType<any>
export const Profiles: ComponentType<any>
export const Projector: ComponentType<any>
export const Protection: ComponentType<any>
export const QRcode: ComponentType<any>
export const Quarantine: ComponentType<any>
export const Question: ComponentType<any>
export const Reader: ComponentType<any>
export const RefreshSync: ComponentType<any>
export const Reload: ComponentType<any>
export const Remotedesktop: ComponentType<any>
export const Reports: ComponentType<any>
export const Restore: ComponentType<any>
export const RotateLeft: ComponentType<any>
export const RotateRight: ComponentType<any>
export const Router: ComponentType<any>
export const Run: ComponentType<any>
export const SaaS: ComponentType<any>
export const SafeClosed: ComponentType<any>
export const SafeEmpty: ComponentType<any>
export const SafeFull: ComponentType<any>
export const SafeKids: ComponentType<any>
export const Sandbox: ComponentType<any>
export const Scale: ComponentType<any>
export const Scan: ComponentType<any>
export const Script: ComponentType<any>
export const Search: ComponentType<any>
export const SearchSimplified: ComponentType<any>
export const Server: ComponentType<any>
export const Settings1: ComponentType<any>
export const Settings2: ComponentType<any>
export const SettingsControl: ComponentType<any>
export const ShieldSelfdefense: ComponentType<any>
export const Shredder: ComponentType<any>
export const SignIn: ComponentType<any>
export const SignOut: ComponentType<any>
export const SimCard: ComponentType<any>
export const SmartCleaner: ComponentType<any>
export const SmartFridge: ComponentType<any>
export const SmartLock: ComponentType<any>
export const Smartplug: ComponentType<any>
export const SmartWasher: ComponentType<any>
export const SmartWatch: ComponentType<any>
export const SmokeDetector: ComponentType<any>
export const Sort: ComponentType<any>
export const SSDDrive: ComponentType<any>
export const Star: ComponentType<any>
export const Storage: ComponentType<any>
export const Store: ComponentType<any>
export const Streamingdongle: ComponentType<any>
export const Support: ComponentType<any>
export const Support2: ComponentType<any>
export const Task: ComponentType<any>
export const Teen: ComponentType<any>
export const TextAntiphishing: ComponentType<any>
export const Thermostat: ComponentType<any>
export const Threats: ComponentType<any>
export const Time: ComponentType<any>
export const TouchID: ComponentType<any>
export const TrustedAppMode: ComponentType<any>
export const TV: ComponentType<any>
export const UnknownDevice: ComponentType<any>
export const UnknownDrive: ComponentType<any>
export const UnknownNetworkDevice: ComponentType<any>
export const Unlock: ComponentType<any>
export const Upgrade: ComponentType<any>
export const Upload: ComponentType<any>
export const VoiceAssistant: ComponentType<any>
export const VPN: ComponentType<any>
export const VulnerabilityScan: ComponentType<any>
export const Warning: ComponentType<any>
export const WaterSensor: ComponentType<any>
export const Wearable: ComponentType<any>
export const Web: ComponentType<any>
export const WebProtection: ComponentType<any>
export const WhoCalls: ComponentType<any>
export const WifiExtender: ComponentType<any>
export const Wizard: ComponentType<any>
